# The Site Settings
timezone: America/New_York
lang: en-US

title: DevScraps
tagline: Software creation and destruction
description: >-
  I spend most of my time performing the act of software creation and destruction,
  this place is about that, and whatever else I hit my head up against.

url: https://papz.github.io

github:
  username: papz
  repo: ""
  branch: master

twitter:
  username: paulangelll

social:
  name: Paul Angell
  email: ""
  links:
    - https://github.com/papz

google_analytics:
  id: ""

cdn:
  enabled: true
  base: ""

assets:
  self_hosted: false

pwa:
  enabled: false

paginate: 10
paginate_path: /page/:num/

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: {}

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:name/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js
    values:
      swcache: true

exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .ruby-version
  - .devcontainer
  - .vscode
  - .idea

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
